In [19]:
import pandas as pd

files = {
    "Dijkstra": "results/standard_1000_results.csv",
    "Bidirectional": "results/bidirectional_1000_results.csv",
    "CH": "results_augmented/bidirectional_1000_results.csv"
}

dfs = []
for algo, path in files.items():
    df = pd.read_csv(path)
    df["algorithm"] = algo
    dfs.append(df)

df = pd.concat(dfs, ignore_index=True)

df.head()

        start      target  distance  relaxed    time_ns algorithm
0   324701905   451765414       985    13112    7302333  Dijkstra
1   366531079  2090465415     19557  1095151  350188709  Dijkstra
2  1879019756  2370730743     17134  1071220  317394916  Dijkstra
3  1164769653  1168741235     16953   851627  245504250  Dijkstra
4   308542236    31233798      6558   394654  149742208  Dijkstra

In [25]:
df["time_ms"] = df["time_ns"] / 1e6 # milliseconds
df["time_μs"] = df["time_ns"] / 1e3 # microseconds
df.head()

,start,target,distance,relaxed,time_ns,algorithm,time_ms,time_μs
0,324701905,451765414,985,13112,7302333,Dijkstra,7.302333,7302.333
1,366531079,2090465415,19557,1095151,350188709,Dijkstra,350.188709,350188.709
2,1879019756,2370730743,17134,1071220,317394916,Dijkstra,317.394916,317394.916
3,1164769653,1168741235,16953,851627,245504250,Dijkstra,245.504250,245504.250
4,308542236,31233798,6558,394654,149742208,Dijkstra,149.742208,149742.208

In [29]:
di = df[df['algorithm'] == "Dijkstra"]
bidi = df[df['algorithm'] == "Bidirectional"]
ch = df[df['algorithm'] == "CH"]

ch.head()

,start,target,distance,relaxed,time_ns,algorithm,time_ms,time_μs
2000,324701905,451765414,985,664,836792,CH,0.836792,836.792
2001,366531079,2090465415,19557,15582,3826209,CH,3.826209,3826.209
2002,1879019756,2370730743,17134,17009,2597708,CH,2.597708,2597.708
2003,1164769653,1168741235,16953,12713,1918917,CH,1.918917,1918.917
2004,308542236,31233798,6558,5152,765584,CH,0.765584,765.584

In [31]:
print(di.info())
di.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   start      1000 non-null   int64
 1   target     1000 non-null   int64
 2   distance   1000 non-null   int64
 3   relaxed    1000 non-null   int64
 4   time_ns    1000 non-null   int64
 5   algorithm  1000 non-null   object
 6   time_ms    1000 non-null   float64
 7   time_μs    1000 non-null   float64
dtypes: float64(2), int64(5), object(1)
memory usage: 70.3+ KB
None

,start,target,distance,relaxed,time_ns,time_ms,time_μs
count,1.000000e+03,1.000000e+03,1000.000000,1.000000e+03,1.000000e+03,1000.000000,1000.000000
mean,1.662169e+09,1.742223e+09,9602.436000,5.933740e+05,1.545874e+08,154.587398,154587.397611
std,1.489156e+09,1.532112e+09,5139.640229,3.378698e+05,9.691830e+07,96.918299,96918.299065
min,1.170890e+05,6.765310e+05,81.000000,2.640000e+02,5.016700e+04,0.050167,50.167000
25%,3.724103e+08,4.135358e+08,5446.500000,3.020035e+05,7.011661e+07,70.116614,70116.614250
50%,1.196612e+09,1.230663e+09,8993.500000,5.854970e+05,1.460673e+08,146.067334,146067.333500
75%,2.498496e+09,2.727213e+09,13637.750000,8.886912e+05,2.354204e+08,235.420437,235420.437250
max,5.395488e+09,5.422689e+09,25840.000000,1.175216e+06,4.631613e+08,463.161333,463161.333000

In [32]:
print(bidi.info())
bidi.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 1000 to 1999
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   start      1000 non-null   int64
 1   target     1000 non-null   int64
 2   distance   1000 non-null   int64
 3   relaxed    1000 non-null   int64
 4   time_ns    1000 non-null   int64
 5   algorithm  1000 non-null   object
 6   time_ms    1000 non-null   float64
 7   time_μs    1000 non-null   float64
dtypes: float64(2), int64(5), object(1)
memory usage: 70.3+ KB
None

,start,target,distance,relaxed,time_ns,time_ms,time_μs
count,1.000000e+03,1.000000e+03,1000.000000,1.000000e+03,1.000000e+03,1000.000000,1000.000000
mean,1.662169e+09,1.742223e+09,9602.436000,4.675432e+05,1.236281e+08,123.628096,123628.095889
std,1.489156e+09,1.532112e+09,5139.640229,3.365160e+05,9.689383e+07,96.893827,96893.826648
min,1.170890e+05,6.765310e+05,81.000000,1.680000e+02,3.145900e+04,0.031459,31.459000
25%,3.724103e+08,4.135358e+08,5446.500000,1.787375e+05,3.809777e+07,38.097771,38097.771000
50%,1.196612e+09,1.230663e+09,8993.500000,3.760860e+05,9.210777e+07,92.107771,92107.771000
75%,2.498496e+09,2.727213e+09,13637.750000,8.328385e+05,2.188802e+08,218.880198,218880.198000
max,5.395488e+09,5.422689e+09,25840.000000,1.132571e+06,3.581691e+08,358.169125,358169.125000

In [33]:
print(ch.info())
ch.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 2000 to 2999
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   start      1000 non-null   int64
 1   target     1000 non-null   int64
 2   distance   1000 non-null   int64
 3   relaxed    1000 non-null   int64
 4   time_ns    1000 non-null   int64
 5   algorithm  1000 non-null   object
 6   time_ms    1000 non-null   float64
 7   time_μs    1000 non-null   float64
dtypes: float64(2), int64(5), object(1)
memory usage: 70.3+ KB
None

,start,target,distance,relaxed,time_ns,time_ms,time_μs
count,1.000000e+03,1.000000e+03,1000.000000,1000.000000,1.000000e+03,1000.000000,1000.000000
mean,1.662169e+09,1.742223e+09,9630.979000,8903.236000,5.249889e+05,0.524989,524.988884
std,1.489156e+09,1.532112e+09,5141.863736,5110.861196,6.496614e+05,0.649661,649.661369
min,1.170890e+05,6.765310e+05,81.000000,63.000000,9.125000e+03,0.009125,9.125000
25%,3.724103e+08,4.135358e+08,5466.250000,5053.750000,2.584485e+05,0.258448,258.448500
50%,1.196612e+09,1.230663e+09,9012.000000,7783.000000,4.198125e+05,0.419813,419.812500
75%,2.498496e+09,2.727213e+09,13658.750000,12713.250000,6.646250e+05,0.664625,664.625000
max,5.395488e+09,5.422689e+09,25840.000000,22496.000000,1.761496e+07,17.614959,17614.959000

In [34]:
time_stats = {
    'Dijkstra': {
        'mean': di['time_μs'].mean(),
        'median': di['time_μs'].median(),
        'min': di['time_μs'].min(),
        'max': di['time_μs'].max()
    },
    'Bidirectional': {
        'mean': bidi['time_μs'].mean(),
        'median': bidi['time_μs'].median(),
        'min': bidi['time_μs'].min(),
        'max': bidi['time_μs'].max()
    },
    'CH': {
        'mean': ch['time_μs'].mean(),
        'median': ch['time_μs'].median(),
        'min': ch['time_μs'].min(),
        'max': ch['time_μs'].max()
    }
}

relaxed_stats = {
    'Dijkstra': {
        'mean': di['relaxed'].mean(),
        'median': di['relaxed'].median(),
        'min': di['relaxed'].min(),
        'max': di['relaxed'].max()
    },
    'Bidirectional': {
        'mean': bidi['relaxed'].mean(),
        'median': bidi['relaxed'].median(),
        'min': bidi['relaxed'].min(),
        'max': bidi['relaxed'].max()
    },
    'CH': {
        'mean': ch['relaxed'].mean(),
        'median': ch['relaxed'].median(),
        'min': ch['relaxed'].min(),
        'max': ch['relaxed'].max()
    }
}

In [42]:
# # create latex tabulars
# time_latex = r"""\begin{tabular}{@{}rllll@{}}
# \toprule
# \multicolumn{5}{c}{Query running time (\mu s)} \\ \midrule
# \multicolumn{1}{l}{\textbf{}} & \textbf{mean} & \textbf{median} & \textbf{min} & \textbf{max} \\ \midrule
# Dijkstra & """ + f"{time_stats['Dijkstra']['mean']:.2f} & {time_stats['Dijkstra']['median']:.2f} & {time_stats['Dijkstra']['min']:.2f} & {time_stats['Dijkstra']['max']:.2f}" + r""" \\
# Bidirectional & """ + f"{time_stats['Bidirectional']['mean']:.2f} & {time_stats['Bidirectional']['median']:.2f} & {time_stats['Bidirectional']['min']:.2f} & {time_stats['Bidirectional']['max']:.2f}" + r""" \\
# CH & """ + f"{time_stats['CH']['mean']:.2f} & {time_stats['CH']['median']:.2f} & {time_stats['CH']['min']:.2f} & {time_stats['CH']['max']:.2f}" + r""" \\ \bottomrule
# \end{tabular}"""

# relaxed_latex = r"""\begin{tabular}{@{}rllll@{}}
# \toprule
# \multicolumn{5}{c}{Relaxed edges} \\ \midrule
# \multicolumn{1}{l}{\textbf{}} & \textbf{mean} & \textbf{median} & \textbf{min} & \textbf{max} \\ \midrule
# Dijkstra & """ + f"{relaxed_stats['Dijkstra']['mean']:.2f} & {relaxed_stats['Dijkstra']['median']:.2f} & {int(relaxed_stats['Dijkstra']['min'])} & {int(relaxed_stats['Dijkstra']['max'])}" + r""" \\
# Bidirectional & """ + f"{relaxed_stats['Bidirectional']['mean']:.2f} & {relaxed_stats['Bidirectional']['median']:.2f} & {int(relaxed_stats['Bidirectional']['min'])} & {int(relaxed_stats['Bidirectional']['max'])}" + r""" \\
# CH & """ + f"{relaxed_stats['CH']['mean']:.2f} & {relaxed_stats['CH']['median']:.2f} & {int(relaxed_stats['CH']['min'])} & {int(relaxed_stats['CH']['max'])}" + r""" \\ \bottomrule
# \end{tabular}"""

# create latex tabulars
time_latex = r"""\begin{tabular}{@{}lrrrr@{}}
\toprule
\multicolumn{5}{c}{Query running time (\mu s)} \\ \midrule
\textbf{} & \textbf{mean} & \textbf{median} & \textbf{min} & \textbf{max} \\ \midrule
Dijkstra & """ + f"{int(time_stats['Dijkstra']['mean']):,} & {int(time_stats['Dijkstra']['median']):,} & {int(time_stats['Dijkstra']['min']):,} & {int(time_stats['Dijkstra']['max']):,}" + r""" \\
Bidirectional & """ + f"{int(time_stats['Bidirectional']['mean']):,} & {int(time_stats['Bidirectional']['median']):,} & {int(time_stats['Bidirectional']['min']):,} & {int(time_stats['Bidirectional']['max']):,}" + r""" \\
CH & """ + f"{int(time_stats['CH']['mean']):,} & {int(time_stats['CH']['median']):,} & {int(time_stats['CH']['min']):,} & {int(time_stats['CH']['max']):,}" + r""" \\ \bottomrule
\end{tabular}"""

relaxed_latex = r"""\begin{tabular}{@{}lrrrr@{}}
\toprule
\multicolumn{5}{c}{Relaxed edges} \\ \midrule
\textbf{} & \textbf{mean} & \textbf{median} & \textbf{min} & \textbf{max} \\ \midrule
Dijkstra & """ + f"{int(relaxed_stats['Dijkstra']['mean']):,} & {int(relaxed_stats['Dijkstra']['median']):,} & {int(relaxed_stats['Dijkstra']['min']):,} & {int(relaxed_stats['Dijkstra']['max']):,}" + r""" \\
Bidirectional & """ + f"{int(relaxed_stats['Bidirectional']['mean']):,} & {int(relaxed_stats['Bidirectional']['median']):,} & {int(relaxed_stats['Bidirectional']['min']):,} & {int(relaxed_stats['Bidirectional']['max']):,}" + r""" \\
CH & """ + f"{int(relaxed_stats['CH']['mean']):,} & {int(relaxed_stats['CH']['median']):,} & {int(relaxed_stats['CH']['min']):,} & {int(relaxed_stats['CH']['max']):,}" + r""" \\ \bottomrule
\end{tabular}"""

In [43]:
# save tabulars
with open('../../report/latex/tabular/time.tex', 'w') as f:
    f.write(time_latex)

with open('../../report/latex/tabular/relaxed.tex', 'w') as f:
    f.write(relaxed_latex)

print("Saved!")

Saved!